Fix the test workflow.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -39,14 +39,15 @@ jobs:
           path: |
             ./godot/bin
           key: godot-${{ env.GODOT_VERSION }}
-      - name: Build Godot Editor
-        if: steps.godot-restore.outputs.cache-hit != 'true'
+      - if: steps.godot-restore.outputs.cache-hit != 'true'
+        name: Build Godot Editor
         shell: sh
         run: |
           cd godot
           scons target=editor platform=windows
         # scons target=editor platform=linux
-      - name: Save Godot Editor
+      - if: steps.godot-restore.outputs.cache-hit != 'true'
+        name: Save Godot Editor
         id: godot-save
         uses: actions/cache/save@v4
         with:
@@ -58,17 +59,37 @@ jobs:
       - name: Build GDExtension Debug Build
         shell: sh
         run: |
-          scons optimize=debug target=template_debug platform=windows arch=x86_64 precision=single optimize=debug custom_api_file=./demo/extension_api.json
-        # scons optimize=debug target=template_debug platform=linux arch=x86_64 precision=single optimize=debug custom_api_file=./demo/extension_api.json
+          scons optimize=debug target=template_debug platform=windows arch=x86_64 precision=single custom_api_file=./demo/extension_api.json
+        # scons optimize=debug target=template_debug platform=linux arch=x86_64 precision=single custom_api_file=./demo/extension_api.json
+
+      - name: Create test output file
+        shell: sh
+        run: |
+          touch test_output.txt
 
       - name: Run tests
+        shell: sh
         run: |
-          ./godot/bin/godot.windows.editor.x86_64 --headless --quit --path ./demo
-        # ./godot/bin/godot.linuxbsd.editor.x86_64 --headless --quit --path ./demo
+          ./godot/bin/godot.windows.editor.x86_64 --headless --quit --path ./demo &> test_output.txt
+        # ./godot/bin/godot.linuxbsd.editor.x86_64 --headless --quit --path ./demo &> test_output.txt
 
-      # TODO: Only needed for Windows?
-      # # Clean up compilation files.
-      # - name: Windows - Delete compilation files
-      #   shell: pwsh
-      #   run: |
-      #     Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
+      - name: Check test output
+        shell: sh
+        run: |
+          if grep -q "SnoreCore test result: ALL TESTS PASSED" test_output.txt; then
+            echo "All tests passed successfully."
+          else
+            echo "Tests failed. Check test_output.txt for details."
+            exit 1
+          fi
+
+      - name: Clean up test output file
+        shell: sh
+        run: |
+          rm test_output.txt
+
+      # Clean up compilation files.
+      - name: Delete compilation files
+        shell: sh
+        run: |
+          rm -rf bin/
